### ISSUE TITLE
Unity version mismatch and missing scripts

### ISSUE THREAD

**Issue by DanielDoe** [truegod1205/HololensEyeTracking#1]
Here are the build settings:
**Build enviroments :**
Unity 2019.3.14
Microsoft Mixed Reality Toolkit (MRTK)
Visual Studio 2019

However, upon adding the project I get asked to install unity 2022 and visual studio 2022. Also, upon opening the scene, there are some missing scripts in some game objects.re

Here is a snapshot of the version mismatch:
![image](https://github.com/truegod1205/HololensEyeTracking/assets/30290716/3bd22ebb-faf6-46c4-8cff-0538bc7b2423)

Here is a sample missing files problem:
![image](https://github.com/truegod1205/HololensEyeTracking/assets/30290716/651212e5-b7a9-4ca0-8c7f-cbdf48c51f3c)
![image](https://github.com/truegod1205/HololensEyeTracking/assets/30290716/f679d46c-5573-4375-9f6f-115f347aaf94)

Any help to get this project to run will be much appreciated. Many thanks

**Comment by truegod1205** [comment]
Hello Daniel, thank you for your report. I have tested and reproduced the issue as well.
Currently, I will add the missing files during the upload and provide installation steps in the Readme file.
I will also try building the project with Unity 2022.
This might take some time, and once updated, I will commit again.
Thank you once again for your feedback.

**Comment by DanielDoe** [comment]
Is it possible to share the Unity 2019.3.14 working version at your convenience please ? I would love to test it out and collect some eye tracking data for my project. Many thanks
I tried to build a new project from scratch but there are some missing files like you pointed out to get the project to work.
![image](https://github.com/truegod1205/HololensEyeTracking/assets/30290716/ae149ca9-bf90-4418-ac96-69eab848b05f)

**Comment by truegod1205** [comment]
Hi, I have fixed the errors related to expired or missing files. After pulling the new commit, there should be no errors during compile time or run time. However, this project is a case I worked on independently in the past, and I don't have a Hololens device at hand to test it now. You can still refer to this repository for the usage of MRTK, but I cannot guarantee that it will function correctly.

**Comment by DanielDoe** [comment]
Works like magic, I really appreciate your help. Kindly let me know if you have any paper I could cite from my project. Also, could you add my wechat so I can discuss some project ideas with you please? I look forward to hearing from you and many thanks indeed!

**Comment by truegod1205** [comment]
I'm glad that this project could be of help to you. However, as mentioned in the previous comment, this is a commissioned project, and I have only implemented the functionality without any associated theory or subsequent data to share. Unfortunately, I may not be able to assist you in that aspect. I wish you the best of luck with your project.
